version: '3'

services:
  # Game server
  game_server:
    build:
      context: ./game_server
      dockerfile: Dockerfile
    image: yulinzhihou/tlsf_gs:v0.1
    volumes:
      - "${SHARED_DIR}/workspace:/home"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: ${RESTART}
    links:
      - tlbbdb
      - webdb

  # Game database
  tlbbdb:
  build:
    context: ./tlbbdb
    image: yulinzhihou/tlsf_tlbbdbserver:v0.1
    volumes:
      - "${SHARED_DIR}/tlbbdb/mysql:/var/lib/mysql"
     ports:
      - "${HOST_MYSQL_PORT}:${TLBB_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "qepyjfnfss1314."
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "tlbbdb"
    restart: ${RESTART}

  # Web database
  webdb:
    build:
      context: ./webdb
      image: yulinzhihou/tlsf_webdbserver:v0.1
      volumes:
        - "${SHARED_DIR}/webdb/mysql:/var/lib/mysql"
      ports:
        - "${HOST_MYSQL_PORT}:${WEB_MYSQL_PORT}"
      environment:
        MYSQL_ROOT_PASSWORD: "qepyjfnfss1314."
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: "web"
      restart: ${RESTART}